version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 850186067537.dkr.ecr.ap-northeast-2.amazonaws.com
      - REPOSITORY_URI=850186067537.dkr.ecr.ap-northeast-2.amazonaws.com/oauth-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - ENVIROMENT_PARMS=$(aws ssm get-parameter --name "/oauth/enviroment" --output json --with-decryption)
      - echo $ENVIROMENT_PARMS | sed ':a;N;$!ba;s/\n/\\n/g' | jq ".Parameter.Value" -r > .env
      - echo Loaded .env file
      - cat .env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Push completed on `date`
